### ISSUE TITLE
Could not perform sync: Status Name - MUST BE A STRING

### ISSUE THREAD

**Issue by DaveStLou** [UniversalDevicesInc/UD-Mobile-Android#3] opened 2020-11-29 21:03 UTC
Initial sync is failing with the following message: 
COULD NOT PERFORM SYNC
Error:
java.lang.illegalArgumentException: Nls Stats Names - Name - MUST BE A STRING

Only option is to cancel sync.

![Screenshot_20201129-145038](https://user-images.githubusercontent.com/16002402/100553599-59ca3d80-3254-11eb-852a-fde68af96295.png)

**Comment by JavierRefuerzo** [comment] 2020-11-30 02:40
Hi @DaveStLou,
I added all Go2ISY testers as Alpha testers for UD Mobile and Google is serving some email list testers with the wrong version.  Please verify app version number as I think this issue was resolved during internal testing. I removed all email testers just now but it has been a persistent issue.
Thanks!

**Comment by daveinglis** [comment] 2020-11-30 14:46
I have the same issue with version 0.27

**Comment by JavierRefuerzo** [comment] 2020-11-30 15:19
Hi @daveinglis ,

I believe this is a node server missing status name causing the issue. Status will now be named "Node Serve Sync Issue" and an error will be presented to the user to notify the Node Server Dev.

Pushed version 0.28, please do let me know if the issue is resolved and which node server is causing the issue.
Thanks

**Comment by daveinglis** [comment] 2020-11-30 16:56
Just tried 0.28 and got another (similar) error:
![Screenshot_20201130-114137](https://user-images.githubusercontent.com/5224890/100639402-1f6ba980-3303-11eb-9b7b-eeefec2e2ab8.png)

**Comment by JavierRefuerzo** [comment] 2020-11-30 17:19
Thanks,
Pushed update 0.29 to catch missing command name, will now be raw value.
As before please do let me know the node server so it can be reviewed.

**Comment by daveinglis** [comment] 2020-11-30 18:37
0.29 sync succeeded.  The nodeserver that it reported as having issues is Number 5 which looks to be the MQTT node server in my polyglot instance (https://github.com/exking/udi-mqtt-poly.git). Note, I don't have it configured with any MQTT endpoints.

![Screenshot_20201130-132409](https://user-images.githubusercontent.com/5224890/100649792-f5b97f00-3310-11eb-952b-152ab2de8e67.png)

**Comment by JavierRefuerzo** [comment] 2020-11-30 19:05
Hi @daveinglis ,

Thanks for your help resolving this issue.   It appears these 3 names are listed as "Name" instead of "NAME" will run this by the others to see if we should accept both cases or request it be corrected.

**Comment by DaveStLou** [comment] 2020-11-30 22:35
Hi @JavierRefuerzo

I'm running version 0.29 now and I'm no longer getting the original error. 

Instead I'm getting the error below. FYI The referenced NodeServer is MQTT.

![Screenshot_20201130-162514](https://user-images.githubusercontent.com/16002402/100673744-9ae05180-3329-11eb-90e8-9d64ccad2d23.png)

**Comment by JavierRefuerzo** [comment] 2020-11-30 22:40
Thanks @DaveStLou ,
This should not affect functionality aside from these three command names not having human readable values. It appears these 3 names are listed as "Name" instead of "NAME" in NLS, will run this by the others to see if we should accept both cases or request it be corrected.

**Comment by JavierRefuerzo** [comment] 2020-12-01 19:04
@daveinglis , @DaveStLou 
Per Chris these values should be upper case as they may not be accepted in the ISY in all places. I have created a pull request in MQTT fixing this issue.  https://github.com/exking/udi-mqtt-poly/pull/7#issue-530510101

**Closed by JavierRefuerzo** 2020-12-01 19:04 UTC
