### ISSUE TITLE
Installation Experience - Sync Errors

### ISSUE THREAD

**Issue by gviliunas** [UniversalDevicesInc/UD-Mobile-Android#13] opened 2020-12-02 18:41 UTC
I'm using a Google Pixel 3a phone with Android 11
ISY Version 5.3.1
UD Mobile version: 0.30

1. Downloaded UD Mobile from the Google store.

2. Entered ISY Portal credentials - Save
3. See Remote Connection Settings - Save
4. Sync ISY with UD Mobile - Yes

    Observe lots of transfer activity
    1st try, the sync stalls with java.net.SocketTimeoutException: timeout (no Screenshot)
    2nd try, try again. This time stalls at Inserting: Network Resources (See Screenshot attached)

5. 3rd try: Notice that on the Remote Connection Settings page there is an "Advanced Settings" area.
6. In Advanced Settings, entered IP and credentials for Local Port Settings
7. Clicked to Add New Local Network - Populated with current WIFI info (Thanks for that button!) - Save
8. Select to Add New Local Network and click on the WIFI SSID previously added - Save
9. Sync - Notice this is much faster than the previous sync via the ISY Portal.
10. Received "Finished with Error" message (See Screenshot attached)
11. 4th try: Back into Settings, try sync again. This time the sync finished with no errors.

Although I had not had a need for mobile ISY access, I like the look and feel of this app. I can see myself making use of this to check light and thermostat status when I'm away

 

Try 3 - Using Local Port Connection.jpg

Try 2 - Using ISY Portal Connection.jpg
![Try 2 - Using ISY Portal Connection](https://user-images.githubusercontent.com/75389409/100916604-d0508080-348a-11eb-98f8-0ef8a19600b7.jpg)
![Try 3 - Using Local Port Connection](https://user-images.githubusercontent.com/75389409/100916616-d47c9e00-348a-11eb-8e8f-0565a04e11b7.jpg)

**Comment by JavierRefuerzo** [comment] 2020-12-03 02:25
Hi @gviliunas ,
Can you verify the app version number (settings>about), we had errors similar to this which have been fixed.  If you have automatic updates turned on for Google Play, we will need to verify the error persists in v0.30.  To do this without changing your current settings you can setup a new system and disable at the bottom of advanced. Disable will allow sync but will not open a session for the ISY subscription when exiting system settings.

Based on your errors I think I may have to increase the read timeout if they are persistent.
Thanks for the report!

**Comment by gviliunas** [comment] 2020-12-04 17:06
Hi Javi,

 

I uninstalled UD Mobile and then tried to re-install.  I can confirm the version I installed was ver .30

 

When the portal sync reached the Z-Wave portion, it stalled and then I received an Error( IOException)java.net.socketTimeout Exception: timeout.  

This was followed ~30 seconds later by Error 500, Error 500, Error 503 

And later by ERROR!! nodeServerFileObjects array is null for family enum: 1 PLEASE NOTIFY DEVELOPER

 

Regards,

 

Greg

**Comment by gviliunas** [comment] 2020-12-04 17:16
Hi Javi,

 

As a follow up to my last message. 

I setup the local network settings and my first re-sync succeeded with an error  (Sorry, didn’t capture this)

I did 1 more sync and it succeeded without error.

 

Greg

**Comment by mkohanim** [comment] 2020-12-04 17:28
Greg,

How many node servers do you have in the cloud?

With kind regards,

******************************
  Michel Kohanim
  CEO

  (p) 818.631.0333
  http://www.universal-devices.com<http://www.universal-devices.com/>
******************************

**Comment by gviliunas** [comment] 2020-12-04 17:39
Hi Michel,

 

I don’t use the cloud. I have a total of 10 NS ALL of these are local . Nine of these are installed in Polisy (The Hue Emulator is stopped as it currently has a problem that Jimbo is working) and One (Presence Poly) is installed on an RPI

 

Regards,

 

Greg Viliunas 

204-2388 Western Parkway

Vancouver, BC  V6T 2K4

778-990-8939

**Comment by mkohanim** [comment] 2020-12-04 17:41
Thanks Greg. How’s the traffic on your ISY? It might be that there’s just too much traffic.

With kind regards,

******************************
  Michel Kohanim
  CEO

  (p) 818.631.0333
  http://www.universal-devices.com<http://www.universal-devices.com/>
******************************

**Comment by gviliunas** [comment] 2020-12-04 18:04
Hi Michel,

 

Not sure how to exactly gauge this on the ISY – there isn’t any type of load meter that I know of...  Let me describe my environment and maybe this will help.

 

I am home alone now (and at the time that I re-loaded UD Mobile). There are no motion lights triggering programs, etc. going on.

 

According to ISY-Inventory, I have:

Total Nodes: 339

Z-Wave: 195

State Variables: 157

Scenes: 61

Node Server Nodes: 80

Programs: 676

Insteon: 64

Int Variables: 99

 

There are 12 active programs running

These are all battery or NS heartbeat monitors

 

The 9 NS running on Polisy are:

ISY Portal

Harmony Hub

LiFX

Hue Emulator (Installed but currently stopped)

WeatherBit

TimeData

ISY-Inventory

Wireless Tag

Virtual

Ping

 

Here is a TOP from Polisy:

 



 

 

 

The 1 NS running on an RPI is:

Presence Poly

 

There are no cloud NS installed

 

 

Does this help?

Let me know if I can gather anything more.

 

Regards,

 

Greg Viliunas 

204-2388 Western Parkway

Vancouver, BC  V6T 2K4

778-990-8939

       bug4

**Comment by mkohanim** [comment] 2020-12-04 18:06
Thank you greg. Based on your topology, I think the issue is timeout. Please note that the initial synch will have to download all this through the portal. If you don’t have the same issue locally, then I am almost certain that the issue is timeout.

With kind regards,

******************************
  Michel Kohanim
  CEO

  (p) 818.631.0333
  http://www.universal-devices.com<http://www.universal-devices.com/>
******************************

**Comment by gviliunas** [comment] 2020-12-04 18:13
Agreed, the sync works as expected locally. I would expect that, okay, sync may have timeouts when done through the portal but, in normal use (portal or local) with small update changes, I expect this should not be a problem.

 

This looks like a good app. Previously I had no interest in phone access to my ISY….. After trying this, I will call myself a convert J

 

Regards,

 

Greg Viliunas 

204-2388 Western Parkway

Vancouver, BC  V6T 2K4

778-990-8939

       bug4

**Comment by mkohanim** [comment] 2020-12-04 18:20
I agree … the normal processing should not be impacted. It’s just the initial synch. @Javier, can we increase the synch time?

I am so very glad to hear that you are now a convert. Because, I am as well. I never used a mobile app for ISY. I just used the browser. But, with node servers, the UD Ajax is crippled. Thank you Javier!

With kind regards,

******************************
  Michel Kohanim
  CEO

  (p) 818.631.0333
  http://www.universal-devices.com<http://www.universal-devices.com/>
******************************

**Comment by JavierRefuerzo** [comment] 2020-12-04 20:42
Hi @gviliunas and @mkohanim ,

I suspect it is a different problem related to requesting the z-wave files. This error is similar to the errors received when the app was asking for z-wave files from ISYs which did not have them.  

@mkohanim is there an instance of a non-zwave ISY running which I can run a test against?  The error should not have happened with a non-zwave ISY, but I assumed it was not an issue if I just did not make the call when the feature was not installed.

@gviliunas ,
Thank you for you time and testing. Please let me try to run a test against the z-wave call to see where this error originates, then we can continue.

**Comment by mkohanim** [comment] 2020-12-04 20:47
HI @javi,

I don’t have any accessible instances of ISY without Z-Wave. Sorry. Perhaps we can ask on the forum?

With kind regards,

******************************
  Michel Kohanim
  CEO

  (p) 818.631.0333
  http://www.universal-devices.com<http://www.universal-devices.com/>
******************************

**Comment by JavierRefuerzo** [comment] 2020-12-04 21:25
@gviliunas ,

If you are willing to assist us in finding the issue, I have a couple of options. If these options do not work for you, we will continue to investigate the issue when it can be reproduced.  


For either option please send correspondence to my email    javier@universal-devices.com

Option 1: 

Add me as a user in your portal account, I will need a window of about an hour to run a sync with your ISY to find the issue, this can be any time convenient for you.  After this time, you can delete me as a user.

Option 2: 

Execute a series of network requests from a browser and return the information to us. 

Get the URL to ISY from the app “Remote URL” then append the following and return.


#Gets the Zwave file names 
/rest/profiles/family/4/profile/1/files 
 
# Gets Node Definitions  
 /rest/zwave/node/0/def/get
 
#Gets Editor Definitions 
/rest/profiles/family/4/profile/1/download/EDITOR/EDITORS.XML 
 
#Gets Name/Language Definitions 
/rest/profiles/family/4/profile/1/download/NLS/EN_US.TXT 
 
The file names request will be small, all others should be a large amount of data. 

Thank you!

**Comment by gviliunas** [comment] 2020-12-04 21:26
FYI:

 

Just to clarify. 

1.       Normal operation (after the initial local sync) of z-wave devices is working properly via UD Mobile. I can turn Z-wave lights on/off and the performance is snappy.

2.       Large packet (1500 byte) ping times from my desktop (on same net as ISY) is a solid 82-83ms   (ping –t  –l  1500 my.isy.io)

 

Greg Viliunas

**Comment by JavierRefuerzo** [comment] 2020-12-04 22:01
Thanks @gviliunas ,

I think you and I replied at the same time,  please see my comments above.

That time It is far below the 15/60 second defaults.  I do believe we may be able to find the issue in the files requested above.

**Comment by gviliunas** [comment] 2020-12-04 22:09
Hi Javi,

 

Better to let you in as an admin. You may see other things as you look.

 

Username: <your email>

Password: BugKiller1

 

 

The system should be pretty quiet. There may be some activity when I leave at 2:30-ish

Then quiet until ~5:30-ish

 

 

Cheers!

 

Greg Viliunas 

204-2388 Western Parkway

Vancouver, BC  V6T 2K4

778-990-8939

       bug4

**Comment by mkohanim** [comment] 2020-12-04 22:11
@javi, please change the password as soon as you login. It’s sent on a public channel. @gviliunas, thank you very much …

With kind regards,

******************************
  Michel Kohanim
  CEO

  (p) 818.631.0333
  http://www.universal-devices.com<http://www.universal-devices.com/>
******************************

**Comment by gviliunas** [comment] 2020-12-04 22:12
Javi, 

 

P.S.  You don’t need to do this now. Anytime is okay with me. Let me know when you are done…

 

Greg

 

Greg Viliunas 

204-2388 Western Parkway

Vancouver, BC  V6T 2K4

778-990-8939

       bug4

**Comment by Javi** [comment] 2020-12-04 22:12
I don't think I'm the one you wanted to @ lol

**Comment by JavierRefuerzo** [comment] 2020-12-04 23:15
@gviliunas, Thank you. Looking into it now. 
@mkohanim Password is changed

**Comment by JavierRefuerzo** [comment] 2020-12-04 23:18
@gviliunas ,

I am done, please remove me from your account.
Will push version 0.32 soon which should fix the issue soon.

@mkohanim,  will send report to you via email.

**Comment by gviliunas** [comment] 2020-12-05 14:55
Hi Javi,

 

You did it!

 

I just uninstalled UD Mobile and re-installed v 0.32. The portal sync completed without any error. The app is working well.

 

Thanks for your hard work!

 

 

Greg Viliunas 

204-2388 Western Parkway

Vancouver, BC  V6T 2K4

778-990-8939

       bug4

**Comment by JavierRefuerzo** [comment] 2020-12-05 16:22
Hi @gviliunas ,
Thank you for your assistance.
Also the TimeDate Poly has an issue so status will show raw values until fixed by the node server dev.
Reported here: https://forum.universal-devices.com/topic/28797-new-isy-time-data-poly/?do=findComment&comment=302904

Best,
Javier

**Closed by JavierRefuerzo** 2020-12-05 16:22 UTC
